import {createAction, props} from '@ngrx/store';
import {Page} from '../shared/constants';
import {Bike} from "../shared/models/bike";
import {Weather} from "../shared/models/weather";

export const setCurrentPage = createAction('[Page] Set', props<{ currentPage: Page }>());
export const setSelectedBike = createAction('[Bike] Set', props<{ selectedBike: Bike }>());
export const incrementBikes = createAction('[Bike] Increment');
export const incrementBikesSuccess = createAction('[Bike] Increment Success', props<{ bikes: Bike[] }>());
export const incrementBikesFailure = createAction('[Bike] Increment Failure', props<{ error: any }>());
export const updateSelectedBike = createAction('[Bike] Update', props<{ selectedBikeId: number }>());
export const updateSelectedBikeSuccess = createAction('[Bike] Update Success', props<{ selectedBike: Bike }>());
export const updateSelectedBikeFailure = createAction('[Bike] Update Failure', props<{ error: any }>());
export const addBike = createAction('[Bike] Add', props<{ bike: Bike }>());
export const addBikeSuccess = createAction('[Bike] Add Success');
export const addBikeFailure = createAction('[Bike] Add Failure', props<{ error: any }>());
export const editBike = createAction('[Bikes] Edit', props<{ bike: Bike }>());
export const editBikeSuccess = createAction('[Bikes] Edit Success');
export const editBikeFailure = createAction('[Bikes] Edit Failure', props<{ error: any }>());
export const deleteBike = createAction('[Bike] Delete', props<{ bikeId: number }>());
export const deleteBikeSuccess = createAction('[Bike] Delete Success');
export const deleteBikeFailure = createAction('[Bike] Delete Failure', props<{ error: any }>());
export const viewWeather = createAction('[Weather] View');
export const viewWeatherSuccess = createAction('[Weather] View Success', props<{ weather: Weather }>());
export const viewWeatherFailure = createAction('[Weather] View Failure', props<{ error: any }>());
